name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v2
      
      - name: Create env file
        run: |
          echo "const SUPABASE_URL = '${{ secrets.SUPABASE_URL }}';" > env.js
          echo "const SUPABASE_KEY = '${{ secrets.SUPABASE_KEY }}';" >> env.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
